### ISSUE TITLE
failed to import _ARC4

### ISSUE THREAD

**Issue by grepwood** [prestodb/presto-admin#61]
```
root@presto-server:/opt/prestoadmin# ./presto-admin
Traceback (most recent call last):
  File "/opt/prestoadmin/presto-admin-install/local/lib/python2.7/site-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
  File "/opt/prestoadmin/presto-admin-install/local/lib/python2.7/site-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/opt/prestoadmin/presto-admin-install/local/lib/python2.7/site-packages/paramiko/transport.py", line 66, in <module>
    from Crypto.Cipher import Blowfish, AES, DES3, ARC4
  File "/opt/prestoadmin/presto-admin-install/local/lib/python2.7/site-packages/Crypto/Cipher/ARC4.py", line 66, in <module>
    from Crypto.Cipher import _ARC4
ImportError: /opt/prestoadmin/presto-admin-install/local/lib/python2.7/site-packages/Crypto/Cipher/_ARC4.so: undefined symbol: PyUnicodeUCS2_FromString

There was a problem importing our SSH library (see traceback above).
Please make sure all dependencies are installed and importable.
```
This happens on Ubuntu 14.04 after installing using the offline installer.
Edit: Could be related to issue #60 due to it not being CentOS.

**Comment by cawallin** [comment]
The offline installer currently is only for CentOS/RHEL.  Have you tried the online installer? You can make it by doing the following:

```
virtualenv venv
source venv/bin/activate
python setup.py develop
pip install wheel
make dist-online
```

**Comment by grepwood** [comment]
Works like a charm!
Only needed to do:
```
python setup.py develop
pip install wheel
make dist-online
```

**Comment by cawallin** [comment]
I also just added the online installer to the 0.1.0 release download page.

It's usually better practice to use virtualenvs for python, so you don't pollute your python library space, but I'm glad it worked!
